// String 7

#include<stdio.h>
#include<conio.h>
void main()
{
  int i;
  char *n,*e,*s,*t;
  clrscr();
  printf("Enter a string n: ");
  scanf("%s",n);

  printf("Enter a string e: ");
  scanf("%s",e);

  printf("Enter a string s: ");
  scanf("%s",s);

  printf("Enter a string t: ");
  scanf("%s",t);

  printf("String n is=%s\n\n",n);
  printf("String e is=%s\n\n",e);
  printf("String s is=%s\n\n",s);
  printf("String t is=%s\n\n",t);
  getch();
}